# Generated by Django 5.2.7 on 2025-10-11 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, null=True, upload_to='')),
                ('location', models.CharField(max_length=100)),
                ('tel', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('working_hours', models.CharField(max_length=10)),
                ('type', models.CharField(choices=[('business', 'Business'), ('customer', 'Customer')], default='Customer', max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
