# Generated by Django 5.2.7 on 2025-10-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_userprofile_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='tel',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
