# Generated by Django 5.2.7 on 2025-10-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_alter_userprofile_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='working_hours',
            field=models.CharField(blank=True),
        ),
    ]
