# Generated by Django 5.2.7 on 2025-10-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerdetails',
            name='revisions',
            field=models.IntegerField(),
        ),
    ]
