# Generated by Django 5.2.7 on 2025-10-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_alter_offerdetails_revisions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerdetails',
            name='price',
            field=models.FloatField(),
        ),
    ]
