# Generated by Django 5.2.7 on 2025-10-29 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_alter_offerdetails_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'verbose_name': 'Offer Media'},
        ),
    ]
