# Generated by Django 5.2.7 on 2025-10-30 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_alter_offer_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
